defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport to release/protocol/v0.3.x branch
    conditions:
      - base=main
      - label=backport/v0.3.x
    actions:
      backport:
        branches:
          - release/protocol/v0.3.x
  - name: backport to release/indexer/v1.x branch
    conditions:
      - base=main
      - label=backport/indexer/v1.x
    actions:
      backport:
        branches:
          - release/indexer/v1.x
  - name: backport to release/protocol/v1.x branch
    conditions:
      - base=main
      - label=backport/protocol/v1.x
    actions:
      backport:
        branches:
          - release/protocol/v1.x
  - name: backport to release/protocol/v2.x branch
    conditions:
      - base=main
      - label=backport/protocol/v2.x
    actions:
      backport:
        branches:
          - release/protocol/v2.x
  - name: backport to release/indexer/v3.x branch
    conditions:
      - base=main
      - label=backport/indexer/v3.x
    actions:
      backport:
        branches:
          - release/indexer/v3.x
  - name: backport to release/protocol/v3.x branch
    conditions:
      - base=main
      - label=backport/protocol/v3.x
    actions:
      backport:
        branches:
          - release/protocol/v3.x
  - name: backport to release/indexer/v4.x branch
    conditions:
      - base=main
      - label=backport/indexer/v4.x
    actions:
      backport:
        branches:
          - release/indexer/v4.x
  - name: backport to release/protocol/v4.x branch
    conditions:
      - base=main
      - label=backport/protocol/v4.x
    actions:
      backport:
        branches:
          - release/protocol/v4.x
  - name: backport to release/indexer/v5.x branch
    conditions:
      - base=main
      - label=backport/indexer/v5.x
    actions:
      backport:
        branches:
          - release/indexer/v5.x
  - name: backport to release/protocol/v5.x branch
    conditions:
      - base=main
      - label=backport/protocol/v5.x
    actions:
      backport:
        branches:
          - release/protocol/v5.x
  - name: backport to release/protocol/v5.1.x branch
    conditions:
      - base=main
      - label=backport/protocol/v5.1.x
    actions:
      backport:
        branches:
          - release/protocol/v5.1.x
  - name: backport to release/protocol/v5.2.x branch
    conditions:
      - base=main
      - label=backport/protocol/v5.2.x
    actions:
      backport:
        branches:
          - release/protocol/v5.2.x
  - name: backport to release/indexer/v6.x branch
    conditions:
      - base=main
      - label=backport/indexer/v6.x
    actions:
      backport:
        branches:
          - release/indexer/v6.x
  - name: backport to release/protocol/v6.x branch
    conditions:
      - base=main
      - label=backport/protocol/v6.x
    actions:
      backport:
        branches:
          - release/protocol/v6.x

