defaults:
  actions:
    backport:
      assignees:
        - "{{ author }}"

pull_request_rules:
  - name: backport to release/protocol/v0.3.x branch
    conditions:
      - base=main
      - label=backport/v0.3.x
    actions:
      backport:
        branches:
          - release/protocol/v0.3.x
  - name: backport to release/indexer/v1.x branch
    conditions:
      - base=main
      - label=backport/indexer/v1.x
    actions:
      backport:
        branches:
          - release/indexer/v1.x
  - name: backport to release/protocol/v1.x branch
    conditions:
      - base=main
      - label=backport/protocol/v1.x
    actions:
      backport:
        branches:
          - release/protocol/v1.x
  - name: backport to release/protocol/v2.x branch
    conditions:
      - base=main
      - label=backport/protocol/v2.x
    actions:
      backport:
        branches:
          - release/protocol/v2.x
  - name: backport to release/indexer/v3.x branch
    conditions:
      - base=main
      - label=backport/indexer/v3.x
    actions:
      backport:
        branches:
          - release/indexer/v3.x
  - name: backport to release/protocol/v3.x branch
    conditions:
      - base=main
      - label=backport/protocol/v3.x
    actions:
      backport:
        branches:
          - release/protocol/v3.x
