package v_6_0_0

import (
	store "cosmossdk.io/store/types"
	slinkytypes "github.com/dydxprotocol/slinky/pkg/types"
	marketmapmoduletypes "github.com/dydxprotocol/slinky/x/marketmap/types"

	"github.com/dydxprotocol/v4-chain/protocol/app/upgrades"
	accountplustypes "github.com/dydxprotocol/v4-chain/protocol/x/accountplus/types"
	listingtypes "github.com/dydxprotocol/v4-chain/protocol/x/listing/types"
	revsharetypes "github.com/dydxprotocol/v4-chain/protocol/x/revshare/types"
)

const (
	UpgradeName = "v6.0.0"
)

var (
	Upgrade = upgrades.Upgrade{
		UpgradeName: UpgradeName,
		StoreUpgrades: store.StoreUpgrades{
			Added: []string{
				listingtypes.StoreKey,
				revsharetypes.StoreKey,
				marketmapmoduletypes.StoreKey,
				accountplustypes.StoreKey,
			},
		},
	}

	DefaultMarketMapParams = marketmapmoduletypes.Params{
		MarketAuthorities: []string{"dydx10d07y265gmmuvt4z0w9aw880jnsr700jnmapky"},
		Admin:             "dydx10d07y265gmmuvt4z0w9aw880jnsr700jnmapky",
	}

	DefaultMarketMap = marketmapmoduletypes.MarketMap{
		Markets: map[string]marketmapmoduletypes.Market{
			"ADA/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "ADA", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "ADAUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "ADAUSDT", NormalizeByPair: &slinkytypes.
						CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "ADA-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "ADA_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "adausdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "ADAUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "ADA-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "ADAUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "ADA-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"APE/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "APE", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "APEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "APE-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "APE_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "APEUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "APE-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "APEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "APE-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"APT/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "APT", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "APTUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "APTUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "APT-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "APT_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "aptusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "APT-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "APTUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "APT-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			}, "ARB/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "ARB", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "ARBUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "ARBUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "ARB-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "ARB_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "arbusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "ARB-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "ARBUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "ARB-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			}, "ATOM/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "ATOM", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "ATOMUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "ATOMUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "ATOM-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "ATOM_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "ATOMUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "ATOM-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "ATOMUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "ATOM-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"AVAX/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "AVAX", Quote: "USD"},
					Decimals:         0x8,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "AVAXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "AVAXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "AVAX-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "AVAX_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "avaxusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "AVAXUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "AVAX-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "AVAX-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			}, "BCH/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "BCH", Quote: "USD"},
					Decimals:         0x7,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "BCHUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "BCHUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "BCH-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "BCH_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "bchusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "BCHUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "BCH-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "BCHUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "BCH-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			}, "BLUR/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "BLUR", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "coinbase_ws", OffChainTicker: "BLUR-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "BLUR_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "BLURUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "BLUR-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "BLURUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "BLUR-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"BTC/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "BTC", Quote: "USD"},
					Decimals:         0x5,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "BTCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "BTCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "BTC-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "btcusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "XXBTZUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "BTC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "BTCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "BTC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			}, "COMP/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "COMP", Quote: "USD"},
					Decimals:         0x8,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "COMPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "COMP-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "COMP_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "COMPUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "COMPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "COMP-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"CRV/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "CRV", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "CRVUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "CRV-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "CRV_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "CRVUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "CRV-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "CRVUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "CRV-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"DOGE/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "DOGE", Quote: "USD"},
					Decimals:         0xb,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "DOGEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "DOGEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "DOGE-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "DOGE_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "dogeusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "XDGUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "DOGE-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "DOGEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "DOGE-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"DOT/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "DOT", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "DOTUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "DOTUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "DOT-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "DOT_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "DOTUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "DOT-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "DOTUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "DOT-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"DYDX/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "DYDX", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "DYDXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "DYDXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "DYDX_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "DYDX-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "DYDXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "DYDX-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"ETC/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "ETC", Quote: "USD"},
					Decimals:         0x8,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "ETCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "ETC-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "ETC_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "etcusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "ETC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "ETCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "ETC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"ETH/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "ETH", Quote: "USD"},
					Decimals:         0x6,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "ETHUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "ETHUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "ETH-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "ethusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "XETHZUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "ETH-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "ETHUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "ETH-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"FIL/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "FIL", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "FILUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "FIL-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "FIL_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "filusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "FILUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "FILUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "FIL-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"LDO/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "LDO", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "LDOUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "LDO-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "LDOUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "LDO-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "LDOUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "LDO-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"LINK/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "LINK", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "LINKUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "LINKUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "LINK-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "LINKUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "LINK-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "LINKUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "LINK-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"LTC/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "LTC", Quote: "USD"},
					Decimals:         0x8,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "LTCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "LTCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "LTC-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "ltcusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "XLTCZUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "LTC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "LTCUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "LTC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"MATIC/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "MATIC", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "MATICUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "MATICUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "MATIC-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "MATIC_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "maticusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "MATICUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "MATIC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "MATICUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "MATIC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"MKR/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "MKR", Quote: "USD"},
					Decimals:         0x6,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "MKRUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "MKR-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "MKRUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "MKR-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "MKRUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "MKR-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"NEAR/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "NEAR", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "NEARUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "NEAR-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "NEAR_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "nearusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "NEAR-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "NEARUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "NEAR-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"OP/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "OP", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3, Enabled: true,
					Metadata_JSON: "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "OPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "OP-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "OP_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "OP-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "OPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "OP-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"PEPE/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "PEPE", Quote: "USD"},
					Decimals:         0x10,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "PEPEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "PEPEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "PEPE_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "PEPEUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "PEPE-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "PEPEUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "PEPE-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"SEI/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "SEI", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "SEIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "SEIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "SEI-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "SEI_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "seiusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "SEI-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "SEIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"SHIB/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "SHIB", Quote: "USD"},
					Decimals:         0xf,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "SHIBUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "SHIBUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "SHIB-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "SHIB_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "SHIBUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "SHIB-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "SHIBUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "SHIB-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"SOL/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "SOL", Quote: "USD"},
					Decimals:         0x8,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "SOLUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "SOLUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "SOL-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "solusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "SOLUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "SOL-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "SOLUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "SOL-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"SUI/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "SUI", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "SUIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "SUIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "SUI-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "SUI_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "suiusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "SUI-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "SUIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "SUI-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"TEST/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "TEST", Quote: "USD"},
					Decimals:         0x5,
					MinProviderCount: 0x1,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "volatile-exchange-provider", OffChainTicker: "TEST-USD", NormalizeByPair: nil,
						Invert: false, Metadata_JSON: ""},
				},
			},
			"TRX/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "TRX", Quote: "USD"},
					Decimals:         0xb,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "TRXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "TRXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "TRX_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "trxusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "TRXUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "TRX-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "TRXUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "TRX-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"UNI/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "UNI", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "UNIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "UNIUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "UNI-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "UNI_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "UNIUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "UNI-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "UNI-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"USDT/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "USDCUSDT",
						NormalizeByPair: nil, Invert: true, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "USDCUSDT",
						NormalizeByPair: nil, Invert: true, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "USDT-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "ethusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "ETH", Quote: "USD"}, Invert: true, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "USDTZUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "BTC-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "BTC", Quote: "USD"}, Invert: true, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "USDC-USDT",
						NormalizeByPair: nil, Invert: true, Metadata_JSON: ""},
				},
			},
			"WLD/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "WLD", Quote: "USD"},
					Decimals:         0x9,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "WLDUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "WLDUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "WLD_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "wldusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "WLD-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "WLDUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "WLD-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"XLM/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "XLM", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "XLMUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "XLMUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "XLM-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "XXLMZUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "XLM-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "XLMUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "XLM-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
			"XRP/USD": {
				Ticker: marketmapmoduletypes.Ticker{
					CurrencyPair:     slinkytypes.CurrencyPair{Base: "XRP", Quote: "USD"},
					Decimals:         0xa,
					MinProviderCount: 0x3,
					Enabled:          true,
					Metadata_JSON:    "",
				},
				ProviderConfigs: []marketmapmoduletypes.ProviderConfig{
					{Name: "binance_ws", OffChainTicker: "XRPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "bybit_ws", OffChainTicker: "XRPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "coinbase_ws", OffChainTicker: "XRP-USD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "gate_ws", OffChainTicker: "XRP_USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "huobi_ws", OffChainTicker: "xrpusdt",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "kraken_api", OffChainTicker: "XXRPZUSD",
						NormalizeByPair: nil, Invert: false, Metadata_JSON: ""},
					{Name: "kucoin_ws", OffChainTicker: "XRP-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "mexc_ws", OffChainTicker: "XRPUSDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
					{Name: "okx_ws", OffChainTicker: "XRP-USDT",
						NormalizeByPair: &slinkytypes.CurrencyPair{Base: "USDT", Quote: "USD"}, Invert: false, Metadata_JSON: ""},
				},
			},
		},
	}
)
