version: '3'
services:
  kafka:
    image: blacktop/kafka:2.6
    ports:
      - 9092:9092
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS:
        "to-ender:1:1,\
        to-vulcan:1:1,\
        to-websockets-orderbooks:1:1,\
        to-websockets-subaccounts:1:1,\
        to-websockets-trades:1:1,\
        to-websockets-markets:1:1,\
        to-websockets-candles:1:1,\
        to-websockets-block-height:1:1"
  postgres-test:
    build:
      context: .
      dockerfile: Dockerfile.postgres.local
    ports:
      - 5436:5432
    environment:
      POSTGRES_PASSWORD: dydxserver123
      POSTGRES_USER: dydx_test
      DATADOG_POSTGRES_PASSWORD: dydxserver123
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres.local
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: dydxserver123
      POSTGRES_USER: dydx_dev
      DATADOG_POSTGRES_PASSWORD: dydxserver123
  redis:
    image: redis:5.0.6-alpine
    ports:
      - 6382:6379
