# Use a specific version here to control when an update to a new major version of the datadog agent is performed
# since major releases happen about once a year and contain breaking changes.
FROM public.ecr.aws/datadog/agent:7

ADD conf.d/redisdb.yaml /etc/datadog-agent/conf.d/redisdb.yaml
