global:
  scrape_interval: 100ms  # Adjust this as necessary
  evaluation_interval: 1s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["slinky0:8002"] # ingest side-car metrics in accordance w/ docker-compose env
