FROM klyraprotocol-base

COPY ./testing/snapshotting/snapshot.sh /klyraprotocol/snapshot.sh

RUN go install cosmossdk.io/tools/cosmovisor/cmd/cosmovisor@v1.5.0

ENTRYPOINT ["/klyraprotocol/snapshot.sh"]
