// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dydxprotocol/subaccounts/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgClaimYieldForSubaccount is the Msg/ClaimYieldForSubaccount request type.
type MsgClaimYieldForSubaccount struct {
	Id *SubaccountId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgClaimYieldForSubaccount) Reset()         { *m = MsgClaimYieldForSubaccount{} }
func (m *MsgClaimYieldForSubaccount) String() string { return proto.CompactTextString(m) }
func (*MsgClaimYieldForSubaccount) ProtoMessage()    {}
func (*MsgClaimYieldForSubaccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_16edbf88307684e5, []int{0}
}
func (m *MsgClaimYieldForSubaccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimYieldForSubaccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimYieldForSubaccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimYieldForSubaccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimYieldForSubaccount.Merge(m, src)
}
func (m *MsgClaimYieldForSubaccount) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimYieldForSubaccount) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimYieldForSubaccount.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimYieldForSubaccount proto.InternalMessageInfo

func (m *MsgClaimYieldForSubaccount) GetId() *SubaccountId {
	if m != nil {
		return m.Id
	}
	return nil
}

// MsgClaimYieldForSubaccountResponse is the Msg/ClaimYieldForSubaccount response type.
type MsgClaimYieldForSubaccountResponse struct {
}

func (m *MsgClaimYieldForSubaccountResponse) Reset()         { *m = MsgClaimYieldForSubaccountResponse{} }
func (m *MsgClaimYieldForSubaccountResponse) String() string { return proto.CompactTextString(m) }
func (*MsgClaimYieldForSubaccountResponse) ProtoMessage()    {}
func (*MsgClaimYieldForSubaccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_16edbf88307684e5, []int{1}
}
func (m *MsgClaimYieldForSubaccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgClaimYieldForSubaccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgClaimYieldForSubaccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgClaimYieldForSubaccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgClaimYieldForSubaccountResponse.Merge(m, src)
}
func (m *MsgClaimYieldForSubaccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgClaimYieldForSubaccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgClaimYieldForSubaccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgClaimYieldForSubaccountResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgClaimYieldForSubaccount)(nil), "dydxprotocol.subaccounts.MsgClaimYieldForSubaccount")
	proto.RegisterType((*MsgClaimYieldForSubaccountResponse)(nil), "dydxprotocol.subaccounts.MsgClaimYieldForSubaccountResponse")
}

func init() { proto.RegisterFile("dydxprotocol/subaccounts/tx.proto", fileDescriptor_16edbf88307684e5) }

var fileDescriptor_16edbf88307684e5 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4c, 0xa9, 0x4c, 0xa9,
	0x28, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x2e, 0x4d, 0x4a, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0x29, 0xd6, 0x2f, 0xa9, 0xd0, 0x03, 0x8b, 0x0b, 0x49, 0x20, 0x2b, 0xd1, 0x43,
	0x52, 0x22, 0x25, 0x99, 0x9c, 0x5f, 0x9c, 0x9b, 0x5f, 0x1c, 0x0f, 0x96, 0xd4, 0x87, 0x70, 0x20,
	0x9a, 0xa4, 0xc4, 0x21, 0x3c, 0xfd, 0xdc, 0xe2, 0x74, 0xfd, 0x32, 0x43, 0x10, 0x05, 0x95, 0x10,
	0x49, 0xcf, 0x4f, 0xcf, 0x87, 0x68, 0x00, 0xb1, 0xa0, 0xa2, 0x9a, 0x38, 0x9d, 0x81, 0x60, 0x43,
	0x94, 0x2a, 0x85, 0x70, 0x49, 0xf9, 0x16, 0xa7, 0x3b, 0xe7, 0x24, 0x66, 0xe6, 0x46, 0x66, 0xa6,
	0xe6, 0xa4, 0xb8, 0xe5, 0x17, 0x05, 0xc3, 0xd5, 0x08, 0x99, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30,
	0x2a, 0x30, 0x6a, 0x70, 0x1b, 0xa9, 0xe9, 0xe1, 0x72, 0xb9, 0x1e, 0x42, 0x87, 0x67, 0x4a, 0x10,
	0x53, 0x66, 0x8a, 0x92, 0x0a, 0x97, 0x12, 0x6e, 0x53, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a,
	0x53, 0x8d, 0xe6, 0x30, 0x72, 0x31, 0xfb, 0x16, 0xa7, 0x0b, 0xf5, 0x32, 0x72, 0x89, 0xe3, 0x72,
	0x81, 0x09, 0x6e, 0x5b, 0x71, 0xdb, 0x20, 0x65, 0x43, 0x8e, 0x2e, 0x98, 0xbb, 0xa4, 0x58, 0x1b,
	0x9e, 0x6f, 0xd0, 0x62, 0x74, 0x4a, 0x3d, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07,
	0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86,
	0x28, 0xef, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd, 0xe0, 0x92, 0xa2,
	0xd4, 0xc4, 0x5c, 0xb7, 0xcc, 0xbc, 0xc4, 0xbc, 0xe4, 0x54, 0xdd, 0x00, 0x78, 0xa0, 0x83, 0x85,
	0x75, 0x93, 0x33, 0x12, 0x33, 0xf3, 0xf4, 0xe1, 0x51, 0x51, 0x81, 0x9a, 0x26, 0x2a, 0x0b, 0x52,
	0x8b, 0x93, 0xd8, 0xc0, 0xb2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0xe2, 0xde, 0x14,
	0x3c, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// ClaimYieldForSubaccount claims the yield for the provided subaccount and persists it to state.
	ClaimYieldForSubaccount(ctx context.Context, in *MsgClaimYieldForSubaccount, opts ...grpc.CallOption) (*MsgClaimYieldForSubaccountResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ClaimYieldForSubaccount(ctx context.Context, in *MsgClaimYieldForSubaccount, opts ...grpc.CallOption) (*MsgClaimYieldForSubaccountResponse, error) {
	out := new(MsgClaimYieldForSubaccountResponse)
	err := c.cc.Invoke(ctx, "/dydxprotocol.subaccounts.Msg/ClaimYieldForSubaccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// ClaimYieldForSubaccount claims the yield for the provided subaccount and persists it to state.
	ClaimYieldForSubaccount(context.Context, *MsgClaimYieldForSubaccount) (*MsgClaimYieldForSubaccountResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ClaimYieldForSubaccount(ctx context.Context, req *MsgClaimYieldForSubaccount) (*MsgClaimYieldForSubaccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimYieldForSubaccount not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ClaimYieldForSubaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgClaimYieldForSubaccount)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ClaimYieldForSubaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dydxprotocol.subaccounts.Msg/ClaimYieldForSubaccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ClaimYieldForSubaccount(ctx, req.(*MsgClaimYieldForSubaccount))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dydxprotocol.subaccounts.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClaimYieldForSubaccount",
			Handler:    _Msg_ClaimYieldForSubaccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dydxprotocol/subaccounts/tx.proto",
}

func (m *MsgClaimYieldForSubaccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimYieldForSubaccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimYieldForSubaccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != nil {
		{
			size, err := m.Id.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgClaimYieldForSubaccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgClaimYieldForSubaccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgClaimYieldForSubaccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgClaimYieldForSubaccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != nil {
		l = m.Id.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgClaimYieldForSubaccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgClaimYieldForSubaccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimYieldForSubaccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimYieldForSubaccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Id == nil {
				m.Id = &SubaccountId{}
			}
			if err := m.Id.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgClaimYieldForSubaccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgClaimYieldForSubaccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgClaimYieldForSubaccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
