syntax = "proto3";
package dydxprotocol.canonicalusdc;

import "dydxprotocol/canonicalusdc/canonical_usdc.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/dydxprotocol/v4-chain/protocol/x/canonicalusdc/types";

// GenesisState defines canonical USDC state.
message GenesisState {
  Controls controls = 1 [ (gogoproto.nullable) = false ];
  Ledger ledger = 2 [ (gogoproto.nullable) = false ];
  repeated PendingSettlement pending_settlements = 3
      [ (gogoproto.nullable) = false ];
}
