[package]
name = "dydx-cosmwasm"
version = "0.4.12"
edition = "2021"
description = "Bindings and helpers for cosmwasm contracts to interact with dYdX Chain"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
num-bigint = "0.4.0"
cosmwasm-std = "1.1"
schemars = "0.8.3"
serde = { version = "1.0.127", default-features = false, features = ["derive"] }
serde_repr = "0.1.8"
protobuf = { version = "=3.2.0", features = ["with-bytes"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0"