name: Indexer check building docker image for all services

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'indexer/**'
  push:
    branches:
      - main
      - 'release/indexer/v[0-9]+.[0-9]+.x'  # e.g. release/indexer/v0.1.x
      - 'release/indexer/v[0-9]+.x'  # e.g. release/indexer/v1.x
    paths:
      - 'indexer/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Build and push
  call-build-ecs-service-ender:
    uses: ./.github/workflows/indexer-reusable-build-and-run-docker-image.yml
    with:
      SERVICE: ender
    secrets: inherit

  call-build-ecs-service-comlink:
    uses: ./.github/workflows/indexer-reusable-build-and-run-docker-image.yml
    with:
      SERVICE: comlink
    secrets: inherit

  call-build-ecs-service-socks:
    uses: ./.github/workflows/indexer-reusable-build-and-run-docker-image.yml
    with:
      SERVICE: socks
    secrets: inherit

  call-build-ecs-service-roundtable:
    uses: ./.github/workflows/indexer-reusable-build-and-run-docker-image.yml
    with:
      SERVICE: roundtable
    secrets: inherit

  call-build-ecs-service-vulcan:
    uses: ./.github/workflows/indexer-reusable-build-and-run-docker-image.yml
    with:
      SERVICE: vulcan
    secrets: inherit

  check-build-bazooka:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./indexer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run:
          npm install -g pnpm@6.34.0

      - name: Build and install
        run: |
          pnpm install --loglevel warn --frozen-lockfile
          pnpm run build:prod:all

      - name: Build docker image for bazooka
        id: build-image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --platform amd64 \
            -f Dockerfile.bazooka.remote .

  check-build-auxo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./indexer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run:
          npm install -g pnpm@6.34.0

      - name: Build and install
        run: |
          pnpm install --loglevel warn --frozen-lockfile
          pnpm run build:prod:all

      - name: Build docker image for auxo
        id: build-image
        run: |
          DOCKER_BUILDKIT=1 docker build \
            --platform amd64 \
            -f Dockerfile.auxo.remote .
