name: Indexer Build & Push Images to AWS ECR for Testnet Branch

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - 'release/indexer/v[0-9]+.[0-9]+.x'  # e.g. release/indexer/v0.1.x
      - 'release/indexer/v[0-9]+.x'  # e.g. release/indexer/v1.x
  push:
    branches:
      - main
      - 'release/indexer/v[0-9]+.[0-9]+.x'  # e.g. release/indexer/v0.1.x
      - 'release/indexer/v[0-9]+.x'  # e.g. release/indexer/v1.x
    # TODO(DEC-837): Customize github build and push to ECR by service with paths
  release:
    types: [created, published]

jobs:
  # Build and push to public-testnet
  call-build-and-push-ecs-services-public-testnet:
    name: (Public Testnet) Build and Push ECS Services
    uses: ./.github/workflows/indexer-build-and-push-all-ecr-images.yml
    with:
      ENVIRONMENT: testnet
    secrets: inherit
