name: Indexer reusable build and run with Postgres, Redis, Kafka

on:
  workflow_call:
    inputs:
      COMMAND:
        required: true
        type: string

jobs:
  run_command:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./indexer
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: dydxserver123
          POSTGRES_USER: dydx_test
        ports:
          - 5432:5432
      redis:
        image: redis:5.0.6-alpine
        ports: 
          - 6379:6379
      kafka:
        image: blacktop/kafka:2.6
        env:
          KAFKA_ADVERTISED_HOST_NAME: localhost
          KAFKA_CREATE_TOPICS: 
            "to-ender:1:1,\
            to-vulcan:1:1,\
            to-websockets-orderbooks:1:1,\
            to-websockets-subaccounts:1:1,\
            to-websockets-trades:1:1,\
            to-websockets-markets:1:1,\
            to-websockets-candles:1:1"
        ports:
          - 9092:9092
      
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run:
          npm install -g pnpm@6.34.0

      - name: Build and install
        run: |
          pnpm install --loglevel warn --frozen-lockfile
          pnpm run build:all

      - name: Run command
        run: ${{ inputs.COMMAND }}
        env:
          DB_PORT: 5432
          REDIS_URL: redis://localhost:6379
          REDIS_READONLY_URL: redis://localhost:6379
          RATE_LIMIT_REDIS_URL: redis://localhost:6379
