name: Indexer Build & Push Images to AWS ECR for Testnet Branch

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - releases/testnet
      - 'release/[a-z]+/v[0-9]+.[0-9]+.x'  # e.g. release/ibctestnet/v1.0.x
      - 'release/v[0-9]+.[0-9]+.x'  # e.g. release/v0.0.x
    # TODO(DEC-837): Customize github build and push to ECR by service with paths

jobs:
  # Build and push to testnet env
  call-build-and-push-ecs-services-testnet:
    name: (Testnet) Build and Push ECS Services
    uses: ./.github/workflows/indexer-build-and-push-all-ecr-images.yml
    with:
      ENVIRONMENT: testnet
    secrets: inherit

  # Build and push to public-testnet (aka testnet1 and testnet2 environments)
  call-build-and-push-ecs-services-public-testnet:
    name: (Public Testnet) Build and Push ECS Services
    uses: ./.github/workflows/indexer-build-and-push-all-ecr-images.yml
    with:
      ENVIRONMENT: testnet2
    secrets: inherit
