name: Indexer Lint
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'indexer/**'
  push:
    branches:
      - main
      - 'release/indexer/v[0-9]+.[0-9]+.x'  # e.g. release/indexer/v0.1.x
      - 'release/indexer/v[0-9]+.x'  # e.g. release/indexer/v1.x
    paths:
      - 'indexer/**'

# Ensure only a single instance of this workflow is running, and cancel any that are in-progress
# before this workflow instance starts
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./indexer
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install pnpm
        run:
          npm install -g pnpm@6.34.0

      - name: Install
        run: |
          pnpm install --loglevel warn --frozen-lockfile

      - name: Lint
        run: pnpm run lint:all
