name: Deploy indexer to staging

on:
  push:
    branches:
      -pipeline-indexer-staging
    paths:
      - 'packages/indexer/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
        
    steps:
      - name: Echo Hello World
        run: echo "Hello World"
