name: Deploy indexer to staging

on:
  pull_request:
    types:
      - closed

jobs:
  on-merge:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'pipeline-main-replica'
    runs-on: ubuntu-latest

    steps:
      - name: Echo Hello World
        run: echo "Hello World"