name: Protocol Build & Push Image to AWS ECR

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - 'release/protocol/v[0-9]+.[0-9]+.x'  # e.g. release/protocol/v0.1.x
      - 'release/protocol/v[0-9]+.x'  # e.g. release/protocol/v1.x
  push:
    branches:
      - main
      - 'release/protocol/v[0-9]+.[0-9]+.x'  # e.g. release/protocol/v0.1.x
      - 'release/protocol/v[0-9]+.x'  # e.g. release/protocol/v1.x

jobs:
  build-and-push-mainnet:
    uses: './.github/workflows/protocol-build-and-push-mainnet-base.yml'
    with:
      ECR_REPOSITORY: mainnet-full-node-profiling
      GOFLAGS: '-toolexec=orchestrion toolexec'