name: Protocol Benchmark
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'protocol/**'
  push:
    branches:
      - main
      - 'release/protocol/v[0-9]+.[0-9]+.x'  # e.g. release/protocol/v0.1.x
      - 'release/protocol/v[0-9]+.x'  # e.g. release/protocol/v1.x
    paths:
      - 'protocol/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  benchmark:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protocol
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      -
        name: Ensure `go.mod` is up to date
        run: go mod tidy && git diff --exit-code
      -
        name: Run Benchmarks
        run: make benchmark
