name: Protocol Price Daemon Exchange Integration Tests
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'protocol/daemons/**'
  push:
    branches:
      - main
      - 'release/protocol/v[0-9]+.[0-9]+.x'  # e.g. release/protocol/v0.1.x
      - 'release/protocol/v[0-9]+.x'  # e.g. release/protocol/v1.x
    paths:
      - 'protocol/daemons/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Runs Price Daemon Exchange Integration Tests
  exchange-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protocol
    steps:
      -
        name: Check out repository code
        uses: actions/checkout@v3
      -
        name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
      -
        name: Display go version
        run: go version
      -
        name: Run exchange tests
        run: make test-exchanges
      -
        name: Slack notify on failure
        uses: slackapi/slack-github-action@v1.23.0
        id: slack
        if: ${{ failure() }}
        with:
          # yamllint disable rule:line-length
          payload: |
            {
              "text": "*${{ github.workflow }}* job `${{ github.job }}` result :x: `${{ job.status }}` :x: for commit ${{ github.event.pull_request.html_url || github.event.head_commit.url }}\n>Triggered by `${{ github.actor }}`, Commit hash ${{ github.sha }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*${{ github.workflow }}* job `${{ github.job }}` result :x: `${{ job.status }}` :x: for commit ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ">Triggered by `${{ github.actor }}`, Commit hash ${{ github.sha }}"
                  }
                }
              ]
            }
          # yamllint enable rule:line-length
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ENG_NOTIFY_WEBHOOK }}
