name: Protocol Container Tests
on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - 'protocol/**'
  push:
    branches:
      - main
      - 'release/[a-z]+/v[0-9]+.[0-9]+.x'  # e.g. release/ibctestnet/v1.0.x
      - 'release/v[0-9]+.[0-9]+.x'  # e.g. release/v0.0.x

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  container-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protocol
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.19
      - name: Build images
        run: DOCKER_BUILDKIT=1 make test-container-build
      - name: Run container tests
        run: make test-container
